"""
Generates Source/ML/FilterbankWeights.h for the DeepChromaExtractor.

Run from the Scripts directory:
    python generate_filterbank.py

Writes the exact triangular filter weights from madmom's LogarithmicFilterbank
as a C++ header. Re-run only if filterbank parameters change.
"""

import os

import numpy as np

# Madmom compatibility fix for newer numpy
np.float = float
np.int = int

from madmom.audio.filters import LogarithmicFilterbank

# Must match the parameters baked into the model weights (madmom defaults)
SAMPLE_RATE = 44100
FFT_SIZE = 8192
NUM_BANDS = 24
FMIN = 65.0
FMAX = 2100.0

OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..",
    "Source",
    "ML",
    "FilterbankWeights.h",
)


def main():
    frequencies = np.arange(FFT_SIZE // 2) * SAMPLE_RATE / FFT_SIZE

    fb = LogarithmicFilterbank(
        frequencies,
        num_bands=NUM_BANDS,
        fmin=FMIN,
        fmax=FMAX,
        unique_filters=True,
    )
    fb_array = np.array(fb)  # Shape: (FFT_SIZE/2, num_unique_bands)
    num_output_bands = fb_array.shape[1]

    print(f"Filterbank shape: {fb_array.shape}")
    print(f"  -> {num_output_bands} unique filter bands")

    lines = []
    lines.append("#pragma once")
    lines.append("#include <vector>")
    lines.append("")
    lines.append("// ================================================================")
    lines.append("// Auto-generated by Scripts/generate_filterbank.py - DO NOT EDIT")
    lines.append("//")
    lines.append("// madmom LogarithmicFilterbank parameters:")
    lines.append(f"//   num_bands={NUM_BANDS}, fmin={FMIN}, fmax={FMAX}")
    lines.append(f"//   sample_rate={SAMPLE_RATE}, fft_size={FFT_SIZE}")
    lines.append("//   unique_filters=True, norm_filters=True")
    lines.append(f"// Output: {num_output_bands} filter bands")
    lines.append("// ================================================================")
    lines.append("")
    lines.append("struct FilterBand {")
    lines.append("    std::vector<int> bins;")
    lines.append("    std::vector<float> weights;")
    lines.append("};")
    lines.append("")
    lines.append(f"// {num_output_bands} unique filter bands")
    lines.append("static const std::vector<FilterBand> MADMOM_FILTERBANK = {")

    for band_idx in range(num_output_bands):
        col = fb_array[:, band_idx]
        nonzero = np.nonzero(col)[0]
        weights = col[nonzero]

        peak_bin = int(nonzero[np.argmax(weights)]) if len(nonzero) > 0 else -1
        bins_str = ", ".join(str(int(b)) for b in nonzero)
        weights_str = ", ".join(f"{float(w):.8f}f" for w in weights)

        lines.append(
            f"    {{{{ {bins_str} }}, {{ {weights_str} }}}},  // band {band_idx}, peak bin {peak_bin}"
        )

    lines.append("};")
    lines.append("")

    out_path = os.path.normpath(OUTPUT_PATH)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Written to: {out_path}")


if __name__ == "__main__":
    main()
